(#7) [스케쥴] 세션 노출 순서 개선
droidknights/DroidKnights2021_App pull request #16
Opened 2021-08-07 06:48 UTC by WonJoongLee

## Issue
- close #7 

## Overview (Required)
- json파일에서 `startTime`과 `title`을 기준으로 정렬
- etc->track1->track2 순서를 track1->track2->etc 순서로 개선

## Screenshot
Before | After
:--: | :--:
<img src="https://user-images.githubusercontent.com/57510192/128591038-c836f73a-2333-44ec-ba13-ff8e724c3dd1.PNG" width="300" /> | <img src="https://user-images.githubusercontent.com/57510192/128591040-1dab1fe3-7aac-47a7-b9d3-e6919854e14e.PNG" width="300" />

2021-08-07 08:51 UTC, Pluu requested changes
@WonJoongLee Enum에 영향을 받는 결과가 포함되어있습니다.

2021-08-07 08:51 UTC, Pluu commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedBy { it.room }
@WonJoongLee sortedBy { it. room } 은 Room 객체의 Enum 정의에 영향을 받는 구조입니다.

https://github.com/droidknights/DroidKnights2021_App/blob/main/shared/src/main/java/com/droidknights/app2021/shared/Domain.kt#L20 Room Enum의 순서를 변경해보시면 현상을 확인할 수 있습니다.

2021-08-08 07:39 UTC, WonJoongLee commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedBy { it.room }
코드리뷰 감사합니다. 해당 부분 삭제하도록 하겠습니다!

2021-08-08 07:47 UTC, WonJoongLee commented
Enum 객체 순서에 영향 받는 부분을 삭제했습니다!

2021-08-08 14:41 UTC, Pluu commented
@WonJoongLee 해당 영역을 제거한 상태로는 이슈가 해결되지않습니다. 다시 확인 부탁드립니다.

2021-08-08 14:41 UTC, Pluu commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedBy { it.room }
@WonJoongLee 해당 영역을 제거한 상태로는 이슈가 해결되지않습니다. 다시 확인 부탁드립니다.

2021-08-09 14:27 UTC, WonJoongLee commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedBy { it.room }
궁금한 점이 생겨 질문드립니다!
`it.room`을 통해 트랙 순서를 변경하려고 했는데, 트랙 순서는 [이슈 6번](https://github.com/droidknights/DroidKnights2021_App/issues/6)에서 다루는 것을 확인했습니다. 그래서 `.sortedBy { it.room }` 코드를 삭제하고, 시간과 세션명 순서로 정렬하기 위해 `.sortedWith(compareBy({ it.startTime }, { it.title }))`만 두었습니다.
제가 확인하기로는 앱을 실행했을 때 각 트랙에서 세션들이 시간에 맞춰서 출력되었는데, 혹시 어떤 부분이 해결되지 않았는지 궁금합니다.

2021-08-09 14:59 UTC, Pluu commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedBy { it.room }
@WonJoongLee 리뷰 수정하신 후 PR에 포함되어 있는 스크린샷은 추가로 업데이트 하신걸까요?

이슈 본문의 내용이 갱신되지않아서 리뷰를 남겼습니다.

2021-08-09 15:20 UTC, WonJoongLee commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedBy { it.room }
죄송합니다. 오픈소스 기여가 미숙해서 부족했던 것 같습니다.

PR 본문 내용 중 Overview 부분과 Screenshot 수정했습니다!

2021-08-09 15:37 UTC, Pluu commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedBy { it.room }
@WonJoongLee 괜찮습니다 :) 비슷한 사례가 있을 수 있으니 더 자세하게 질문하도록 저도 반성합니다.

2021-08-09 15:52 UTC, Pluu approved these changes

2021-08-09 15:54 UTC, Pluu commented
@WonJoongLee 해당 작업은 확인은 완료되었습니다. 수고하셨습니다 👏👏👏

2021-08-09 15:54 UTC, merged

2021-08-09 15:59 UTC, WonJoongLee commented
> @WonJoongLee 해당 작업은 확인은 완료되었습니다. 수고하셨습니다 👏👏👏

감사합니다!!