[스케쥴] 트랙 노출 순서 개선
droidknights/DroidKnights2021_App pull request #26
Opened 2021-08-12 13:05 UTC by BeokBeok

## Issue
- close #6

## Overview (Required)
- 트랙  노출 순서를 수정하였습니다 (Track1 > Track2 > Etc)

## Screenshot
Before | After
:--: | :--:
<img src="" width="300" /> | <img src="" width="300" />

2021-08-12 16:12 UTC, Pluu commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedWith(compareBy({ it.room.ordinal }, { it.startTime }, { it.title }))
@BeokBeok Enum의 ordinal을 사용할 경우, Enum 정의 순서에 영향을 받습니다.

혹시 개선이 가능할까요? 어렵다면 별도 이슈로 진행하려고합니다.

2021-08-13 00:02 UTC, BeokBeok commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedWith(compareBy({ it.room.ordinal }, { it.startTime }, { it.title }))
@Pluu 다른 방법으로 개선을 해보도록 하겠습니다 😄 
그런데 혹시 enum이 순서를 가지는 특성을 활용하지 않고 다른 방법으로 해결하시려고 하는 이유가 있을까요? 🤔

2021-08-13 00:13 UTC, Pluu commented on domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt
> +            .sortedWith(compareBy({ it.room.ordinal }, { it.startTime }, { it.title }))
Enum은 도메인에 대한 정의에 가까운 형태로 접근해서 위와 같은 코멘트를 남겼습니다.

정보 자체를 DB화 한다면 우선순위에 대한 정의는 Enum값보다는 별도 Compare가 적절하다고 판단했습니다.

이 내용은 우선순위가 높지않기때문에, 편하게 판단해주셔도 됩니다

2021-08-13 01:28 UTC, BeokBeok commented
@Pluu 다른 방법으로 개선을 해보았습니다 😅

2021-08-13 04:02 UTC, Pluu requested changes
@BeokBeok 개선 작업에 일부 오류가 포함되어있는걸 확인했습니다. 체크 부탁드립니다.

2021-08-13 04:02 UTC, Pluu commented on features/schedule/src/main/java/com/droidknights/app2021/schedule/ScheduleScreen.kt
> +    val rooms = sortedRoomList()
@BeokBeok 해당 로직의 잠재적인 이슈로는 ETC에 해당하는 세션이 없는 경우, pagerState 관련 에러가 발생합니다.

또한 ETC에 해당하는 Indicator가 노출되네요.

2021-08-13 06:51 UTC, BeokBeok commented on features/schedule/src/main/java/com/droidknights/app2021/schedule/ScheduleScreen.kt
> +@Composable
함수 자동 추출 기능을 썼더니 자동으로 어노테이션 붙었네요 😭 
[ad63ceb]

2021-08-13 06:52 UTC, BeokBeok commented on features/schedule/src/main/java/com/droidknights/app2021/schedule/ScheduleScreen.kt
> +    val rooms = sortedRoomList()
앗! 그 부분을 생각을 하지 못했네요
말씀하신 부분 고려해서 수정해보았습니다 🙏 
[2000dfc]

2021-08-13 11:39 UTC, Pluu approved these changes
🚀

2021-08-13 11:39 UTC, merged